In [1]:
import numpy as np
a = np.array([11,15,90])
print(a)
print (a[0])

[11 15 90]
11


In [ ]:
import numpy as np 
a = np.array([[1, 2], [3, 4],[5,6]]) 
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.itemsize)

4


In [ ]:
print(a.dtype)

int32


In [ ]:
import numpy as np 
a = np.array([5,6,9], dtype = complex) 
print(a)

[5.+0.j 6.+0.j 9.+0.j]


In [ ]:
print(a.itemsize)

16


In [ ]:
print(a.size)

3


In [ ]:
print(a.shape)

(3,)


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
a = np.array([[1, 2], [3, 4],[5,6]]) 
print(a.shape)

(3, 2)


In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([ 9, 12])

In [ ]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(a)

1.707825127659933

In [ ]:
a = np.array([[1, 2], [3, 4]])
b=np.array([[5,6],[7,8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np
a = np.array([5,6,9])
a[0:2]

array([5, 6])

In [ ]:
a[-1]

9

In [ ]:
a = np.array([[1, 2,6], [3, 4,9],[5,6,8]]) 
print(a)

[[1 2 6]
 [3 4 9]
 [5 6 8]]


In [ ]:
a[1,2]

9

In [ ]:
a[0:2,2]

array([6, 9])

In [ ]:
a[-1]

array([5, 6, 8])

In [ ]:
a[-1,0:2]

array([5, 6])

In [ ]:
a[:]

array([[1, 2, 6],
       [3, 4, 9],
       [5, 6, 8]])

In [ ]:
a[:,1:3]

array([[2, 6],
       [4, 9],
       [6, 8]])

In [ ]:
for cell in a.flat:
    print(cell)

1
2
6
3
4
9
5
6
8


In [ ]:
a=np.arange(6).reshape(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b=np.arange(6,12).reshape(3,2)

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
a=np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [ ]:
result=np.hsplit(a,3)
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [ ]:
result=np.vsplit(a,2)
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [ ]:
b=a>10
print(b)

[[False False False False False False False False False False False  True
   True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True]]


In [ ]:
a[b]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [ ]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [ ]:
b = a.T 
print(b) 

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [ ]:
for x in np.nditer(b): 
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
for x in np.nditer(b,order='F'):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
for x in np.nditer(b,order='C'):
    print(x)

0
20
40
5
25
45
10
30
50
15
35
55


In [ ]:
for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print(a)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
